import { OrmawaTable } from "../types/ormawa";

export const internalSubmissionList: OrmawaTable[] = [
  {
    id: 1,
    tanggalPendaftaran: "20/06/2026",
    terakhirDiedit: "20/06/2026",
    pic: "John Doe",
    kontakPic: "0867676767",
    namaOrmawa: "BEM Fakultas Ilmu Komputer",
    jenisOrmawa: "BEM",
    namaKabinet: "BEM FILKOM",
    nominasi: ["BEM FILKOM"],
    programKerjaUnggulan: "Program Kerja Unggulan BEM FILKOM",
    status: "approved",
    deskripsiSingkat: "Deskripsi Singkat BEM FILKOM",
    linkDrive:
      "https://drive.google.com/drive/folders/1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p",
  },
  {
    id: 2,
    tanggalPendaftaran: "20/06/2026",
    terakhirDiedit: "20/06/2026",
    pic: "Ghiffary Abdul",
    kontakPic: "0867676767",
    namaOrmawa: "DPM Fakultas Ilmu Komputer",
    jenisOrmawa: "DPM",
    namaKabinet: "DPM FILKOM",
    nominasi: ["DPM FILKOM"],
    programKerjaUnggulan: "Program Kerja Unggulan DPM FILKOM",
    status: "pending",
    deskripsiSingkat: "Deskripsi Singkat DPM FILKOM",
    linkDrive:
      "https://drive.google.com/drive/folders/1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p",
  },
  {
    id: 3,
    tanggalPendaftaran: "20/06/2026",
    terakhirDiedit: "20/06/2026",
    pic: "Imroatus",
    kontakPic: "0867676767",
    namaOrmawa: "Kabinet Departemen Sistem Informasi",
    jenisOrmawa: "HIMA",
    namaKabinet: "Kabinet Departemen Sistem Informasi",
    nominasi: ["Kabinet Departemen Sistem Informasi"],
    programKerjaUnggulan:
      "Program Kerja Unggulan Kabinet Departemen Sistem Informasi",
    status: "rejected",
    deskripsiSingkat: "Deskripsi Singkat Kabinet Departemen Sistem Informasi",
    linkDrive:
      "https://drive.google.com/drive/folders/1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p",
  },
  {
    id: 4,
    tanggalPendaftaran: "20/06/2026",
    terakhirDiedit: "20/06/2026",
    pic: "Muhammad Ibnu",
    kontakPic: "0867676767",
    namaOrmawa: "Nol Derajat Film",
    jenisOrmawa: "UKM",
    namaKabinet: "Nol Derajat Film",
    nominasi: ["Nol Derajat Film"],
    programKerjaUnggulan: "Program Kerja Unggulan Nol Derajat Film",
    status: "approved",
    deskripsiSingkat: "Deskripsi Singkat Nol Derajat Film",
    linkDrive:
      "https://drive.google.com/drive/folders/1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p",
    subKategori: "UKM Film",
    lombaDimenangkan: ["Lomba Film 1", "Lomba Film 2"],
  },
];

export const externalSubmissionList: OrmawaTable[] = [
  {
    id: 1,
    tanggalPendaftaran: "20/06/2026",
    terakhirDiedit: "20/06/2026",
    pic: "John Thor",
    kontakPic: "0867676767",
    namaOrmawa: "BEM Fakultas Ekonomi dan Bisnis",
    jenisOrmawa: "BEM",
    namaKabinet: "BEM FEB",
    nominasi: ["BEM FEB"],
    programKerjaUnggulan: "Program Kerja Unggulan BEM FEB",
    status: "approved",
    deskripsiSingkat: "Deskripsi Singkat BEM FEB",
    linkDrive:
      "https://drive.google.com/drive/folders/1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p",
  },
  {
    id: 2,
    tanggalPendaftaran: "20/06/2026",
    terakhirDiedit: "20/06/2026",
    pic: "Abdul Fatah",
    kontakPic: "0867676767",
    namaOrmawa: "DPM Fakultas Ekonomi dan Bisnis",
    jenisOrmawa: "DPM",
    namaKabinet: "DPM FEB",
    nominasi: ["DPM FEB"],
    programKerjaUnggulan: "Program Kerja Unggulan DPM FEB",
    status: "pending",
    deskripsiSingkat: "Deskripsi Singkat DPM FEB",
    linkDrive:
      "https://drive.google.com/drive/folders/1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p",
  },
  {
    id: 3,
    tanggalPendaftaran: "20/06/2026",
    terakhirDiedit: "20/06/2026",
    pic: "Abdul Fatah",
    kontakPic: "0867676767",
    namaOrmawa: "DPM Fakultas Ekonomi dan Bisnis",
    jenisOrmawa: "HIMA",
    namaKabinet: "HIMA",
    nominasi: ["BEST"],
    programKerjaUnggulan: "Program Kerja Unggulan DPM FEB",
    status: "pending",
    deskripsiSingkat: "Deskripsi Singkat DPM FEB",
    linkDrive:
      "https://drive.google.com/drive/folders/1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p",
  },
  {
    id: 4,
    tanggalPendaftaran: "20/06/2026",
    terakhirDiedit: "20/06/2026",
    pic: "Abdul Fatah",
    kontakPic: "0867676767",
    namaOrmawa: "DPM Fakultas Ekonomi dan Bisnis",
    jenisOrmawa: "UKM",
    namaKabinet: "UKM",
    nominasi: ["UKM"],
    programKerjaUnggulan: "Program Kerja Unggulan DPM FEB",
    status: "pending",
    deskripsiSingkat: "Deskripsi Singkat DPM FEB",
    linkDrive:
      "https://drive.google.com/drive/folders/1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p",
    lombaDimenangkan: [],
    subKategori: "Sub Kategori",
  },
];
